package com.probytemedia.amazingfacts.utils;

/**
 * Created by AABID on 19/4/14.
 */
public class InitializeArrayList {

    InitializeArrayList() {
//        //0
//        AppConstants.allQuotesList.add(".");

        AppConstants.allQuotesList.add("A goldfish's attention span is three seconds.");
        AppConstants.allQuotesList.add("Animals that lay eggs don't have belly buttons.");
        AppConstants.allQuotesList.add("Beavers can hold their breath for 45 minutes under water.");
        AppConstants.allQuotesList.add("Slugs have four noses.");
        AppConstants.allQuotesList.add("Camels have three eyelids.");
        AppConstants.allQuotesList.add("A honey bee can fly at 15mph.");
        AppConstants.allQuotesList.add("A queen bee can lay 800-1,500 eggs per day.");
        AppConstants.allQuotesList.add("A bee has five eyelids.");
        AppConstants.allQuotesList.add("The average speed of a housefly is 4.5 mph.");
        AppConstants.allQuotesList.add("Mosquitoes are attracted to people who just ate bananas.");
        AppConstants.allQuotesList.add("Flamingos turn pink from eating shrimp.");
        AppConstants.allQuotesList.add("Emus and kangaroos cannot walk backward.");
        AppConstants.allQuotesList.add("Cats have over 100 vocal chords.");
        AppConstants.allQuotesList.add("Camel's milk does not curdle.");
        AppConstants.allQuotesList.add("All porcupines float in water.");
        AppConstants.allQuotesList.add("The world's termites outweigh the world's humans 10 to 1.");
        AppConstants.allQuotesList.add("A hummingbird weighs less than a penny.");
        AppConstants.allQuotesList.add("A jellyfish is 95% water.");
        AppConstants.allQuotesList.add("Children grow faster in the spring.");
        AppConstants.allQuotesList.add("Broccoli is the only vegetable that is also a flower.");
        AppConstants.allQuotesList.add("Almonds are part of the peach family.");
        AppConstants.allQuotesList.add("Alaska has the highest percentage of people who walk to work.");
        AppConstants.allQuotesList.add("The San Francisco cable cars are the only mobile national monument.");
        AppConstants.allQuotesList.add("The state of Maine has 62 lighthouses.");
        AppConstants.allQuotesList.add("The only food that does not spoil is honey.");
        AppConstants.allQuotesList.add("The Hawaiian alphabet only has 12 letters.");
        AppConstants.allQuotesList.add("A ball of glass will bounce higher than a ball of rubber.");
        AppConstants.allQuotesList.add("Chewing gum while peeling onions will prevent you from crying.");
        AppConstants.allQuotesList.add("On average a human will spend up to 2 weeks kissing in his/her lifetime.");
        AppConstants.allQuotesList.add("Fish have eyelids.");
        AppConstants.allQuotesList.add("The average human eats 8 spiders in his/her lifetime while sleeping.");
        AppConstants.allQuotesList.add("There are one million ants to every human in the world.");
        AppConstants.allQuotesList.add("Termites eat through wood two times faster when listening to rock music!");
        AppConstants.allQuotesList.add("If you keep a goldfish in a dark room it will eventually turn white.");
        AppConstants.allQuotesList.add("Elephants only sleep two hours a day.");
        AppConstants.allQuotesList.add("A duck's quack doesn't echo.");
        AppConstants.allQuotesList.add("A snail breathes through its foot.");
        AppConstants.allQuotesList.add("Fish cough.");
        AppConstants.allQuotesList.add("An ant's sense of smell is stronger than a dog's.");
        AppConstants.allQuotesList.add("It is possible to lead a cow up stairs but not down.");
        AppConstants.allQuotesList.add("Shrimp can only swim backward.");
        AppConstants.allQuotesList.add("Frogs cannot swallow with their eyes open.");
        AppConstants.allQuotesList.add("A cat's lower jaw cannot move sideways.");
        AppConstants.allQuotesList.add("The bullfrog is the only animal that never sleeps.");
        AppConstants.allQuotesList.add("Elephants are capable of swimming 20 miles per day.");
        AppConstants.allQuotesList.add("Elephants are the only mammals that can't jump.");
        AppConstants.allQuotesList.add("Giraffes have no vocal chords.");
        AppConstants.allQuotesList.add("Cats can hear ultrasound.");
        AppConstants.allQuotesList.add("Despite its hump, a camel has a straight spine.");
        AppConstants.allQuotesList.add("Mosquitoes have 47 teeth.");
        AppConstants.allQuotesList.add("There are 63,360 inches in a mile.");
        AppConstants.allQuotesList.add("Eleven percent of people in the world are left-handed.");
        AppConstants.allQuotesList.add("The average women consumes six pounds of lipstick in her lifetime.");
        AppConstants.allQuotesList.add("The average smell weighs 760 nanograms.");
        AppConstants.allQuotesList.add("A human brain weighs about three pounds.");
        AppConstants.allQuotesList.add("1/4 of the bones in your body are in your feet.");
        AppConstants.allQuotesList.add("You blink over 10,000,000 times a year.");
        AppConstants.allQuotesList.add("A sneeze travels out of your mouth at over 100 miles an hour.");
        AppConstants.allQuotesList.add("Brain waves can be used to power an electric train.");
        AppConstants.allQuotesList.add("The tongue is the fastest healing part of the body.");
        AppConstants.allQuotesList.add("Pigs get sunburned.");
        AppConstants.allQuotesList.add("The lifespan of a taste bud is 10 days.");
        AppConstants.allQuotesList.add("The average human produces 10,000 gallons of saliva in a lifetime.");
        AppConstants.allQuotesList.add("Strawberries contain more vitamin C than oranges.");
        AppConstants.allQuotesList.add("A one-day weather forecast requires about 10 billion math calculations.");
        AppConstants.allQuotesList.add("Americans, on average, eat 18 acres of pizza a day.");
        AppConstants.allQuotesList.add("There are 18 different animal shapes in the animal cracker zoo.");
        AppConstants.allQuotesList.add("The longest one syllable word is \"screeched.\"");
        AppConstants.allQuotesList.add("No word in the English language rhymes with month.");
        AppConstants.allQuotesList.add("Caller ID is illegal in California.");
        AppConstants.allQuotesList.add("There is a town called \"Big Ugly\" in West Virginia.");
        AppConstants.allQuotesList.add("The average person uses 150 gallons of water per day for personal use.");
        AppConstants.allQuotesList.add("The average person spends 2 weeks over his/her lifetime waiting for a traffic light to change.");
        AppConstants.allQuotesList.add("You share your birthday with at least 9 million other people in the world.");
        AppConstants.allQuotesList.add("The average person makes 1,140 phone calls per year.");
        AppConstants.allQuotesList.add("The average person spends about 2 years on the phone in a lifetime.");
        AppConstants.allQuotesList.add("No piece of paper can be folded more than seven times.");
        AppConstants.allQuotesList.add("Alaska is the most eastern and western state in the U.S.");
        AppConstants.allQuotesList.add("There are 119 grooves on the edge of a quarter.");
        AppConstants.allQuotesList.add("About 18 percent of animal owners share their bed with their pet.");
        AppConstants.allQuotesList.add("Alaska has more caribou than people.");
        AppConstants.allQuotesList.add("August has the highest percentage of births.");
        AppConstants.allQuotesList.add("Googol is a number (1 followed by 100 zeros).");
        AppConstants.allQuotesList.add("Oysters can change from one gender to another and back again.");
        AppConstants.allQuotesList.add("The Mona Lisa has no eyebrows.");
        AppConstants.allQuotesList.add("Until the 19th century, solid blocks of tea were used as money in Siberia.");
        AppConstants.allQuotesList.add("A mile on the ocean and a mile on land are not the same distance.");
        AppConstants.allQuotesList.add("A ten gallon hat holds less than one gallon of liquid.");
        AppConstants.allQuotesList.add("The average American walks 18,000 steps a day.");
        AppConstants.allQuotesList.add("The average raindrop falls at seven mph.");
        AppConstants.allQuotesList.add("There are more telephones than people in Washington, D.C.");
        AppConstants.allQuotesList.add("Fish can drown.");
        AppConstants.allQuotesList.add("A kangaroo can jump 30 feet.");
        AppConstants.allQuotesList.add("Lizards communicate by doing push-ups.");
        AppConstants.allQuotesList.add("Squids can have eyes the size of a volleyball.");
        AppConstants.allQuotesList.add("The average American will eat 35,000 cookies in his/her lifetime.");
        AppConstants.allQuotesList.add("A turkey can run at 20 mph.");
        AppConstants.allQuotesList.add("When the moon is directly overhead you weigh slightly less.");
        AppConstants.allQuotesList.add("You burn 20 calories an hour chewing gum.");
        AppConstants.allQuotesList.add("In a year, the average person walks four miles making his or her bed.");
        AppConstants.allQuotesList.add("About half of all Americans are on a diet on any given day.");
        AppConstants.allQuotesList.add("A one-minute kiss burns 26 calories.");
        AppConstants.allQuotesList.add("Frowning burns more calories than smiling.");
        AppConstants.allQuotesList.add("There are more than 30,000 diets on public record.");
        AppConstants.allQuotesList.add("You will burn about 7% more calories walking on hard dirt than on pavement.");
        AppConstants.allQuotesList.add("You would weigh less on the top of a mountain than at sea level.");
        AppConstants.allQuotesList.add("You burn more calories sleeping than watching TV.");
        AppConstants.allQuotesList.add("Licking a stamp burns 10 calories.");
        AppConstants.allQuotesList.add("Smelling apples and/or bananas can help you lose weight.");
        AppConstants.allQuotesList.add("Frogs never drink.");
        AppConstants.allQuotesList.add("Only male turkeys gobble.");
        AppConstants.allQuotesList.add("At birth, a Dalmation is always pure white.");
        AppConstants.allQuotesList.add("The fastest recorded speed of a racehorse was over 43 mph.");
        AppConstants.allQuotesList.add("The oldest known animal was a tortoise, which lived to be 152 years old.");
        AppConstants.allQuotesList.add("Bamboo makes up 99 percent of a panda's diet.");
        AppConstants.allQuotesList.add("The largest fish is the whale shark - it can be over 50 feet long and weigh two tons.");
        AppConstants.allQuotesList.add("The starfish is the only animal that can turn its stomach inside out.");
        AppConstants.allQuotesList.add("Honeybees are the only insects that create a form of food for humans.");
        AppConstants.allQuotesList.add("The hummingbird is the only bird that can fly backwards.");
        AppConstants.allQuotesList.add("The only continent without reptiles or snakes is Antarctica.");
        AppConstants.allQuotesList.add("The only bird that can swim and not fly is a penguin.");
        AppConstants.allQuotesList.add("A duck can't walk without bobbing its head.");
        AppConstants.allQuotesList.add("Beavers were once the size of bears.");
        AppConstants.allQuotesList.add("Seals sleep only one and a half minutes at a time.");
        AppConstants.allQuotesList.add("Pigeons have been trained by the U.S. Coast Guard to spot people lost at sea.");
        AppConstants.allQuotesList.add("A pigeon's feathers are heavier than its bones.");
        AppConstants.allQuotesList.add("A hummingbird's heart beats 1,400 times a minute.");
        AppConstants.allQuotesList.add("Dragonflies have six legs but can't walk.");
        AppConstants.allQuotesList.add("Dolphins can jump up to 20 feet in the air.");
        AppConstants.allQuotesList.add("Koala and humans are the only animals with unique fingerprints.");
        AppConstants.allQuotesList.add("Penguins have an organ above their eyes that converts seawater to fresh water.");
        AppConstants.allQuotesList.add("A crocodile cannot move its tongue.");
        AppConstants.allQuotesList.add("Honeybees navigate by using the sun as a compass.");
        AppConstants.allQuotesList.add("An ant can lift 50 times its own weight.");
        AppConstants.allQuotesList.add("A single coffee tree produces only about a pound of coffee beans per year.");
        AppConstants.allQuotesList.add("Strawberries are the only fruits whose seeds grow on the outside.");
        AppConstants.allQuotesList.add("The city of Los Angeles has three times more automobiles than people.");
        AppConstants.allQuotesList.add("Hawaii is the only U.S. state that grows coffee.");
        AppConstants.allQuotesList.add("Hawaii is the only state with one school district.");
        AppConstants.allQuotesList.add("Holland is the only country with a national dog.");
        AppConstants.allQuotesList.add("The square dance is the official dance of the state of Washington.");
        AppConstants.allQuotesList.add("Hawaii is the only U.S. state never to report a temperature of zero degrees F or below.");
        AppConstants.allQuotesList.add("Q is the only letter in the alphabet not appearing in the name of any U.S. state.");
        AppConstants.allQuotesList.add("Texas is the only state that permits residents to cast absentee ballots from space.");
        AppConstants.allQuotesList.add("Lake Superior is the world's largest lake.");
        AppConstants.allQuotesList.add("The smallest county in America is New York County, better known as Manhattan.");
        AppConstants.allQuotesList.add("Panama is the only place in the world where you can see the sun rise on the Pacific and set on the Atlantic.");
        AppConstants.allQuotesList.add("The tallest man was 8 ft. 11 in.");
        AppConstants.allQuotesList.add("Theodore Roosevelt was the only president who was blind in one eye.");
        AppConstants.allQuotesList.add("The first sport to be filmed was boxing in 1894.");
        AppConstants.allQuotesList.add("The fastest served ball in tennis was clocked at 154 mph in 1963.");
        AppConstants.allQuotesList.add("In 1985, the fastest bicyclist was clocked at 154 mph.");
        AppConstants.allQuotesList.add("The speed limit in NYC was eight mph in 1895.");
        AppConstants.allQuotesList.add("Americans spend more than $630 million a year on golf balls.");
        AppConstants.allQuotesList.add("In 1926, the first outdoor mini-golf courses were built on rooftops in NYC.");
        AppConstants.allQuotesList.add("Swimming pools in the U.S. contain enough water to cover San Francisco.");
        AppConstants.allQuotesList.add("The first TV soap opera debuted in 1946.");
        AppConstants.allQuotesList.add("The first MTV video was \"Video Killed the Radio Star\" by the Buggles.");
        AppConstants.allQuotesList.add("The first TV show ever to be put into reruns was \"The Lone Ranger.\"");
        AppConstants.allQuotesList.add("One alternative title that had been considered for NBC's hit \"Friends\" was \"Insomnia Café.\"");
        AppConstants.allQuotesList.add("The first TV network kids show in the U.S. was \"Captain Kangaroo.\"");
        AppConstants.allQuotesList.add("The temperature of the sun can reach up to 15 million degrees Fahrenheit.");
        AppConstants.allQuotesList.add("The first penny had the motto \"Mind your own business.\"");
        AppConstants.allQuotesList.add("The first vacuum was so large, it was brought to a house by horses.");
        AppConstants.allQuotesList.add("Your eye expands up to 45% when looking at something pleasing.");
        AppConstants.allQuotesList.add("Before mercury, brandy was used to fill thermometers.");
        AppConstants.allQuotesList.add("You have to play ping-pong for 12 hours to lose one pound.");
        AppConstants.allQuotesList.add("One brow wrinkle is the result of 200,000 frowns.");
        AppConstants.allQuotesList.add("The first human-made object to break the sound barrier was a whip.");
        AppConstants.allQuotesList.add("In 1878, the first telephone book ever issued contained only 50 names.");
        AppConstants.allQuotesList.add("The most sensitive parts of the body are the mouth and the fingertips.");
        AppConstants.allQuotesList.add("The eye makes movements 50 times every second.");
        AppConstants.allQuotesList.add("Chinese is the most spoken language in the world.");
        AppConstants.allQuotesList.add("The world's biggest pyramid is not in Egypt, but in Mexico.");
        AppConstants.allQuotesList.add("In 1634, tulip bulbs were a form of currency in Holland.");
        AppConstants.allQuotesList.add("The first bike was called a hobbyhorse.");
        AppConstants.allQuotesList.add("The first sailing boats were built in Egypt.");
        AppConstants.allQuotesList.add("The first ballpoint pens were sold in 1945 for $12.00.");
        AppConstants.allQuotesList.add("The first lighthouse to use electricity was the Statue of Liberty in 1886.");
        AppConstants.allQuotesList.add("The first VCR was made in 1956 and was the size of a piano.");
        AppConstants.allQuotesList.add("The first jukebox was located in San Francisco in 1899.");
        AppConstants.allQuotesList.add("A rainbow can only be seen in the morning or late afternoon.");
        AppConstants.allQuotesList.add("The Capitol building in Washington, D.C. has 365 steps to represent every day of the year.");
        AppConstants.allQuotesList.add("The most used letters in the English language are E, T, A, O, I and N.");
        AppConstants.allQuotesList.add("A male kangaroo is called a boomer.");
        AppConstants.allQuotesList.add("A female kangaroo is called a flyer.");
        AppConstants.allQuotesList.add("There are over 61,000 pizzerias in the U.S.");
        AppConstants.allQuotesList.add("Antarctica is the driest, coldest, windiest, and highest continent on earth.");
        AppConstants.allQuotesList.add("The Sahara Desert stretches farther than the distance from California to New York.");
        AppConstants.allQuotesList.add("Thailand means \"Land of the Free.\"");
        AppConstants.allQuotesList.add("Popcorn was invented by the American Indians.");
        AppConstants.allQuotesList.add("Jupiter spins so fast that there is a new sunrise nearly every 10 hours.");
        AppConstants.allQuotesList.add("The year that read the same upside down was 1961. That won't happen again until 6009.");
        AppConstants.allQuotesList.add("You don't have to be a lawyer to be a Supreme Court Justice.");
        AppConstants.allQuotesList.add("Eleven of the 50 U.S. states are named after an actual person.");
        AppConstants.allQuotesList.add("If you doubled one penny every day for 30 days, you would have $5,368,709.");
        AppConstants.allQuotesList.add("The first person crossed Niagara Falls by tightrope in 1859.");
        AppConstants.allQuotesList.add("The U.S. is the largest country named after an actual person (Amerigo Vespucci).");
        AppConstants.allQuotesList.add("The largest cheesecake ever made weighed 57,508 lbs.");
        AppConstants.allQuotesList.add("The first country to use postcards was Austria.");
        AppConstants.allQuotesList.add("The only one-syllabled U.S. state is Maine.");
        AppConstants.allQuotesList.add("The mouth of the Statue of Liberty is 3 feet wide.");
        AppConstants.allQuotesList.add("Atlantic salmon are capable of leaping 15 feet high.");
        AppConstants.allQuotesList.add("A stamp shaped like a banana was once issued in the country of Tonga.");
        AppConstants.allQuotesList.add("For every human being in the world there is approximately one chicken.");
        AppConstants.allQuotesList.add("Over 1 million Earths would fit inside the Sun.");
        AppConstants.allQuotesList.add("Before 1687 clocks were made with only an hour hand.");
        AppConstants.allQuotesList.add("Add up opposing sides of a dice cue and you'll always get seven.");
        AppConstants.allQuotesList.add("The largest pumpkin ever grown weighed 1,061 lbs.");
        AppConstants.allQuotesList.add("1.3 billion pounds of peanuts are produced in Georgia each year.");
        AppConstants.allQuotesList.add("The average koala sleeps 22 hours each day.");
        AppConstants.allQuotesList.add("Galapagos turtles can take up to three weeks to digest a meal.");
        AppConstants.allQuotesList.add("The largest ball of twine in the US weighs over 17,000.");
        AppConstants.allQuotesList.add("Giraffes can lick their own eyes.");
        AppConstants.allQuotesList.add("Tennessee banned the use of a lasso to catch fish.");
        AppConstants.allQuotesList.add("TV dinners originated in the Artic.");
        AppConstants.allQuotesList.add("Blackboard chalk contains no chalk.");
        AppConstants.allQuotesList.add("A jackrabbit can travel more than 12 feet in one hop.");
        AppConstants.allQuotesList.add("An electric eel can release a charge powerful enough to start 50 cars.");
        AppConstants.allQuotesList.add("Porcupines each have 30,000 quills.");
        AppConstants.allQuotesList.add("The game of basketball was first played using a soccer ball and two peach baskets.");
        AppConstants.allQuotesList.add("Twinkle Twinkle Little Star was composed by Mozart when he was five years old.");
        AppConstants.allQuotesList.add("The Basenji is the only type of dog that does not bark.");
        AppConstants.allQuotesList.add("America's 1st roller coaster was built in 1827 to carry coal from a mine to boats below.");
        AppConstants.allQuotesList.add("There are towns named Sandwich in Illinois and Massachusetts.");
        AppConstants.allQuotesList.add("13 percent of the world's tea comes from Kenya.");
        AppConstants.allQuotesList.add("Tsiology is anything written about tea.");
        AppConstants.allQuotesList.add("There is a town in South Dakota named Tea.");
        AppConstants.allQuotesList.add("The Caspian Sea is actually a lake.");
        AppConstants.allQuotesList.add("Caterpillars have over 2,000 muscles.");
        AppConstants.allQuotesList.add("Detroit has the greatest number of registered bowlers in the U.S.");
        AppConstants.allQuotesList.add("The blue whale's heart is the size of a small car.");
        AppConstants.allQuotesList.add("There are seven letters that look the same upside down as right side up.");
        AppConstants.allQuotesList.add("Great Falls, Montana, is the windiest city in the U.S.");
        AppConstants.allQuotesList.add("The biggest pig in recorded history weighed almost one ton.");
        AppConstants.allQuotesList.add("Cows give more milk when they listen to music.");
        AppConstants.allQuotesList.add("The number of times a cricket chirps in 15 seconds, plus 37, will give you the current air temperature.");
        AppConstants.allQuotesList.add("An ostrich's brain is smaller than its eye.");
        AppConstants.allQuotesList.add("Besides humans, elephants are the only animals that can be taught to stand on their head.");
        AppConstants.allQuotesList.add("Challenger Deep is the deepest point on Earth and can hold 25 Empire State Buildings end to end.");
        AppConstants.allQuotesList.add("The only cactus plantation in the world is in Mississippi.");
        AppConstants.allQuotesList.add("The Nickname of President Hayes's wife was \"Lemonade Lucy.\"");
        AppConstants.allQuotesList.add("If you put all the streets in New York City in a straight line, they would stretch to Japan.");
        AppConstants.allQuotesList.add("The watermelon seed-spitting world record is about 70 feet.");
        AppConstants.allQuotesList.add("The first typewriter was called the \"literary piano\".");
        AppConstants.allQuotesList.add("The \"silk\" of a spider is stronger than steel threads of the same diameter.");
        AppConstants.allQuotesList.add("Britain was the first country to register a patent on polyester.");
        AppConstants.allQuotesList.add("Snoopy is the most common dog name beginning with the letter S.");
        AppConstants.allQuotesList.add("The 1st public message to be transmitted via Morse code was \"A patient waiter is no loser.\"");
        AppConstants.allQuotesList.add("Mongolians invented lemonade around 1299 A.D.");
        AppConstants.allQuotesList.add("There are more French restaurants in New York City than in Paris.");
        AppConstants.allQuotesList.add("There is a town in Alaska called Chicken.");
        AppConstants.allQuotesList.add("The first TV remote control, introduced in 1950, was called Lazy Bones.");
        AppConstants.allQuotesList.add("The only bird who can see the color blue is the owl.");
        AppConstants.allQuotesList.add("Among North Atlantic lobsters, 1 in 5,000 is born bright blue.");
        AppConstants.allQuotesList.add("There are more saunas than cars in Finland.");
        AppConstants.allQuotesList.add("The first food eaten in space by a U.S. astronaut was applesauce.");
        AppConstants.allQuotesList.add("Lemon wood is carved into chess pieces.");
        AppConstants.allQuotesList.add("The original recipe for chocolate contained chili powder instead of sugar.");
        AppConstants.allQuotesList.add("Underwater hockey is played with a 3-pound puck.");
        AppConstants.allQuotesList.add("Playing in a marching band is considered moderate exercise.");
        AppConstants.allQuotesList.add("The act of chewing an apple is a more efficient way to stay awake than caffeine.");
        AppConstants.allQuotesList.add("Bowling pins need to tip over a mere 7 1/2 degrees to fall down.");
        AppConstants.allQuotesList.add("Your breathing rate increases when you start to type.");
        AppConstants.allQuotesList.add("90% of all garlic consumed in the U.S. comes from Gilroy, CA.");
        AppConstants.allQuotesList.add("Manhattan is the only borough in New York City that doesn't have a Main Street.");
        AppConstants.allQuotesList.add("Double Dutch jump rope is considered a cross-training sport.");
        AppConstants.allQuotesList.add("One lemon tree will produce about 1,500 lemons a year.");
        AppConstants.allQuotesList.add("Horseback riding can improve your posture.");
        AppConstants.allQuotesList.add("Colors like red, yellow and orange make you hungry.");
        AppConstants.allQuotesList.add("Dim lights reduce your appetite.");
        AppConstants.allQuotesList.add("At birth a human has 350 bones, but only 206 bones when full grown.");
        AppConstants.allQuotesList.add("Each year, the average American eats about 15 pounds of apples.");
        AppConstants.allQuotesList.add("All lemons are harvested by hand.");
        AppConstants.allQuotesList.add("It took the first man to walk around the world four years, three months and 16 days to complete his journey.");
        AppConstants.allQuotesList.add("Grizzly bears run as fast as the average horse.");
        AppConstants.allQuotesList.add("Today's \"modern\" wrestling moves have been seen in tomb drawings from ancient Egypt.");
        AppConstants.allQuotesList.add("China only has one time zone.");
        AppConstants.allQuotesList.add("Canada has the longest coastline of any country in the world.");
        AppConstants.allQuotesList.add("The amount of concrete used in the Hoover Dam could build a highway from New York to California.");
        AppConstants.allQuotesList.add("The original name of Nashville, Tennessee was Big Salt Lick.");
        AppConstants.allQuotesList.add("If you drive from Los Angeles to Reno, NV, you will be heading west.");
        AppConstants.allQuotesList.add("A compass needle does not point directly north.");
        AppConstants.allQuotesList.add("Mt. Everest has grown one foot over the last 100 years.");
        AppConstants.allQuotesList.add("In ancient Rome, lemons were used as an antidote to all poisons.");
        AppConstants.allQuotesList.add("The height of the Eiffel Tower varies by as much as 6 inches depending on the temperature.");
        AppConstants.allQuotesList.add("Wisconsin has points located farther east than parts of Florida.");
        AppConstants.allQuotesList.add("Four Corners, AZ, is the only place where a person can stand in 4 states at the same time.");
        AppConstants.allQuotesList.add("In 1908, the first lollipop-making machine started in New Haven, CT.");
        AppConstants.allQuotesList.add("One out of every eight residents in the U.S. lives in California.");
        AppConstants.allQuotesList.add("Africa is divided into more countries than any other continent.");
        AppConstants.allQuotesList.add("Heavier, not bigger lemons, produce more juice.");
        AppConstants.allQuotesList.add("Vermont is the only New England state without a seacoast.");
        AppConstants.allQuotesList.add("No only child has been a U.S. President.");
        AppConstants.allQuotesList.add("Leonardo da Vinci could draw with one hand while writing with the other.");
        AppConstants.allQuotesList.add("In 1860, Abraham Lincoln grew a beard at the suggestion of an 11-year-old girl.");
        AppConstants.allQuotesList.add("David Rice Atchison was President of the United States for only one day.");
        AppConstants.allQuotesList.add("The sail fish has been clocked at speeds of over 60 miles per hour.");
        AppConstants.allQuotesList.add("The Library of Congress has 600 miles of shelves.");
        AppConstants.allQuotesList.add("Pennsylvania is misspelled on the Liberty Bell.");
        AppConstants.allQuotesList.add("William Shakespeare was born and died on the same day: April 23.");
        AppConstants.allQuotesList.add("Ketchup was once sold as a medicine.");
        AppConstants.allQuotesList.add("Napoleon suffered from a fear of cats.");
        AppConstants.allQuotesList.add("In 1900, 1/3 of all automobiles in New York City were powered by electricity.");
        AppConstants.allQuotesList.add("The 4th Earl of Sandwich invented the sandwich so he could eat and gamble at the same time.");
        AppConstants.allQuotesList.add("In the Middle Ages, chicken soup was considered an aphrodisiac.");
        AppConstants.allQuotesList.add("All dog breeds except chow-chows have black lips to prevent them from getting sunburned.");
        AppConstants.allQuotesList.add("Connecticut was the first state to pass a Lemon Law in 1982.");
        AppConstants.allQuotesList.add("Ancient Egyptians believed the \"vein of love\" ran from the third finger on the left hand to the heart.");
        AppConstants.allQuotesList.add("The word \"facetious\" features all the vowels in alphabetical order.");
        AppConstants.allQuotesList.add("The standard Chinese typewriter has 1,500 characters.");
        AppConstants.allQuotesList.add("A flea can jump 30,000 times without stopping.");
        AppConstants.allQuotesList.add("O is the oldest letter of the alphabet, dating back to 3000 B.C.");
        AppConstants.allQuotesList.add("The Japanese word \"judo\" means \"the gentle way.\"");
        AppConstants.allQuotesList.add("No two lip impressions are the same.");
        AppConstants.allQuotesList.add("It took Leonardo da Vinci 12 years to paint the lips of Mona Lisa.");
        AppConstants.allQuotesList.add("Lemon sharks can give birth to about 36 babies at one time.");
        AppConstants.allQuotesList.add("Top-performing companies are called \"blue chips\" after the costliest chips in casinos.");
        AppConstants.allQuotesList.add("The name for the space between your eyebrows is \"nasion.\"");
        AppConstants.allQuotesList.add("There is a town called Jackpot in Nevada.");
        AppConstants.allQuotesList.add("The word \"purple\" does not rhyme with any other word in the English language.");
        AppConstants.allQuotesList.add("In the U.S., there are about 15,000 vacuum cleaner-related accidents each year.");
        AppConstants.allQuotesList.add("The Lemon-Yellow Tree Frog is only active in the darkness of night.");
        AppConstants.allQuotesList.add("The legs of bats are too weak to support their weight, so they hang upside down.");
        AppConstants.allQuotesList.add("75% of people wash from top to bottom in the shower.");
        AppConstants.allQuotesList.add("On average, you'll spend a year of your life looking for misplaced objects.");
        AppConstants.allQuotesList.add("Chewing gum was invented in New York City in 1870 by Thomas Adams.");
        AppConstants.allQuotesList.add("The Statue of Liberty features 7 points in her crown- one for each of the continents.");
        AppConstants.allQuotesList.add("The world's first escalator was built in Coney Island, NY, in 1896.");
        AppConstants.allQuotesList.add("The top of the Empire State Building was originally built as a place to anchor blimps.");
        AppConstants.allQuotesList.add("The area code in Cape Canaveral, Fl, is 321.");
        AppConstants.allQuotesList.add("Ohio is the only U.S. state that does not have a rectangular flag.");
        AppConstants.allQuotesList.add("Long Island is the largest island in the Continental U.S.");
        AppConstants.allQuotesList.add("The beaver is the official animal of Canada.");
        AppConstants.allQuotesList.add("Maine produces more toothpicks than any other state in the U.S.");
        AppConstants.allQuotesList.add("The last letter to be added to our alphabet was J.");
        AppConstants.allQuotesList.add("Farmington, Maine celebrates Chester Greenwood Day to honor the inventor of earmuffs.");
        AppConstants.allQuotesList.add("Of all the trees in Australia, 75% are eucalyptus.");
        AppConstants.allQuotesList.add("There are more doughnut shops per capita in Canada than in any other country.");
        AppConstants.allQuotesList.add("There is an underground mushroom in Oregon that measures 3.5 miles across.");
        AppConstants.allQuotesList.add("Of the 92 counties in Indiana, only 5 observe daylight savings time.");
        AppConstants.allQuotesList.add("California and Arizona grow approximately 95% of the fresh lemons in the U.S.");
        AppConstants.allQuotesList.add("The term 007 was derived from 20007, the home zip code of many Washington, D.C. agents.");
        AppConstants.allQuotesList.add("Leonardo da Vinci discovered that a tree's rings reveal its age.");
        AppConstants.allQuotesList.add("The popsicle was invented in 1905 by an 11-year-old boy.");
        AppConstants.allQuotesList.add("The medical term for writer's cramp is graphospasm.");
        AppConstants.allQuotesList.add("A male firefly's light is twice as bright as a female's.");
        AppConstants.allQuotesList.add("It is estimated that the world's oceans contain 10 billion tons of gold.");
        AppConstants.allQuotesList.add("Most cats don't like lemonade.");
        AppConstants.allQuotesList.add("The watersheds that supply water to New York City are roughly the size of Delaware.");
        AppConstants.allQuotesList.add("Cold water weighs less than hot water.");
        AppConstants.allQuotesList.add("Storm clouds hold about 6 trillion raindrops.");
        AppConstants.allQuotesList.add("The weight of the moon is 81 billion tons.");
        AppConstants.allQuotesList.add("Bamboo can grow three feet in one day.");
        AppConstants.allQuotesList.add("A tune that gets stuck in your head is called an earworm.");
        AppConstants.allQuotesList.add("You exhale air at 15 m.p.h.");
        AppConstants.allQuotesList.add("A baboon is a variety of lemon.");
        AppConstants.allQuotesList.add("Butterflies were formerly known by the name Flutterby.");
        AppConstants.allQuotesList.add("A teaspoon contains 120 drops of water.");
        AppConstants.allQuotesList.add("Mexican jumping beans jump to get out of sunlight.");
        AppConstants.allQuotesList.add("The pineapple is a very big berry.");
        AppConstants.allQuotesList.add("Arachibutlphobia is the fear of peanut butter sticking to the roof of your mouth.");
        AppConstants.allQuotesList.add("Pearls dissolve in vinegar.");
        AppConstants.allQuotesList.add("Borborygmi is the noise that your stomach makes when you are hungry.");
        AppConstants.allQuotesList.add("The oil in cashews helps prevent tooth decay.");
        AppConstants.allQuotesList.add("The center of some golf balls contain honey.");
        AppConstants.allQuotesList.add("International tug of war rules state that the rope must be over 100-feet long.");
        AppConstants.allQuotesList.add("In 2003, a 6-year-old from Naples, FL was ticketed for not having a permit for her lemonade stand.");
        AppConstants.allQuotesList.add("On Valentine's Day, there is no charge to get married in the Empire State Building's chapel.");
        AppConstants.allQuotesList.add("Heat, not sunlight, ripens tomatoes.");
        AppConstants.allQuotesList.add("Grapes are the most popular fruit in the world.");
        AppConstants.allQuotesList.add("A housefly hums in the key of F.");
        AppConstants.allQuotesList.add("Endocarp is the edible pulp inside a lemon.");
        AppConstants.allQuotesList.add("Thomas Edison coined the word \"hello\" and introduced it as a way to answer the phone.");
        AppConstants.allQuotesList.add("Way is the most frequently used noun in the English language.");
        AppConstants.allQuotesList.add("The \"high five\" was introduced by a professional baseball player in 1977.");
        AppConstants.allQuotesList.add("Disco means \"I learn\" in Latin.");
        AppConstants.allQuotesList.add("It costs the U.S. government 2.5 cents to produce a quarter.");
        AppConstants.allQuotesList.add("The \"lemon yellow\" crayon was introduced in 1949 and retired in 1990.");
        AppConstants.allQuotesList.add("It is illegal for a portrait of a living person to appear on U.S. postage stamps.");
        AppConstants.allQuotesList.add("Baboons were once trained by Egyptians to wait on tables.");
        AppConstants.allQuotesList.add("The official state gem of Washington is petrified wood.");
        AppConstants.allQuotesList.add("Mount Katahdin in Maine is the first place in the U.S. to get sunlight each morning.");
        AppConstants.allQuotesList.add("Each year, the average person walks the distance from NY to Miami.");
        AppConstants.allQuotesList.add("Lemons are more acidic than vinegar.");
        AppConstants.allQuotesList.add("New York City's public school students represent about 188 different countries.");
        AppConstants.allQuotesList.add("A banana is a giant herb.");
        AppConstants.allQuotesList.add("The first person in the U.S. arrested for speeding was a NYC cab driver.");
        AppConstants.allQuotesList.add("In the U.S., all interstate highways that run east to west are even-numbered.");
        AppConstants.allQuotesList.add("Jack is the most common name in nursery rhymes.");
        AppConstants.allQuotesList.add("A sea lemon is a mollusk that feeds on sponges.");
        AppConstants.allQuotesList.add("Three out of every six Americans live within fifty miles of where they were born.");
        AppConstants.allQuotesList.add("The raised bump reflectors on U.S. roads are named \"Botts dots.\"");
        AppConstants.allQuotesList.add("Nearly 9,000 people injure themselves with a toothpick each year.");
        AppConstants.allQuotesList.add("It is impossible to sneeze with your eyes open.");
        AppConstants.allQuotesList.add("The dragonfly can reach speeds of up to 36 mph.");
        AppConstants.allQuotesList.add("Bamboo can grow over three feet per day.");
        AppConstants.allQuotesList.add("Hippos can open their mouths 180 degrees.");
        AppConstants.allQuotesList.add("Manhattan was the first capital of the United States.");
        AppConstants.allQuotesList.add("About 80 women go into labor on NYC subways every year.");
        AppConstants.allQuotesList.add("The coldest city in the U.S. is International Falls, Minnesota.");
        AppConstants.allQuotesList.add("Christopher Columbus brought the first lemon seeds to America.");
        AppConstants.allQuotesList.add("The largest hailstone ever recorded in the U.S. was 17.5 inches around.");
        AppConstants.allQuotesList.add("The Statue of Liberty's nose is four feet six inches long.");
        AppConstants.allQuotesList.add("The East Antarctic Ice Sheet is as thick as the Alps Mountains are high.");
        AppConstants.allQuotesList.add("The deepest place in the ocean is about seven miles deep.");
        AppConstants.allQuotesList.add("The largest dog litter was 23 puppies.");
        AppConstants.allQuotesList.add("Panda bears eat up to 16 hours a day.");
        AppConstants.allQuotesList.add("Approximately 16,500 people in the U.S. go by the last name Lemon.");
        AppConstants.allQuotesList.add("Bald eagles can swim using a stroke similar to the butterfly stroke.");
        AppConstants.allQuotesList.add("Lifejackets used to be filled with sunflower seeds for flotation.");
        AppConstants.allQuotesList.add("Two trees can create enough oxygen for a family of four.");
        AppConstants.allQuotesList.add("The T-rex's closest living relative is the chicken.");
        AppConstants.allQuotesList.add("Chameleons can move both their eyes in different directions at the same time.");
        AppConstants.allQuotesList.add("The most popular pet name in the United States is 'Max.'");
        AppConstants.allQuotesList.add("Many butterflies and moths are able to taste with their feet.");
        AppConstants.allQuotesList.add("All polar bears are left-handed.");
        AppConstants.allQuotesList.add("The smallest mammal in the world is the bumblebee bat, which weighs less than a penny.");
        AppConstants.allQuotesList.add("A jiffy is an actual time measurement equaling 1/100th of a second.");
        AppConstants.allQuotesList.add("Greyhounds can reach speeds of 45 miles per hour.");
        AppConstants.allQuotesList.add("Apples, peaches and raspberries are all members of the rose family.");
        AppConstants.allQuotesList.add("U.S. paper currency isn't made of paper - it's actually a blend of cotton and linen.");
        AppConstants.allQuotesList.add("The ZIP in the ZIP code stands for Zone Improvement Plan.");
        AppConstants.allQuotesList.add("Kangaroos can't walk backwards.");
        AppConstants.allQuotesList.add("The Empire State Building has 73 elevators.");
        AppConstants.allQuotesList.add("Lemons ripen after you pick them, but oranges do not.");
        AppConstants.allQuotesList.add("There are 118 ridges on the edge of a United States dime.");
        AppConstants.allQuotesList.add("There are 336 dimples on a regulation American golf ball.");
        AppConstants.allQuotesList.add("One acre of peanuts will make 30,000 peanut butter sandwiches.");
        AppConstants.allQuotesList.add("A twit is the technical term for a pregnant goldfish.");
        AppConstants.allQuotesList.add("Antarctica holds 90% of the world's fresh water.");
        AppConstants.allQuotesList.add("The state of Tennessee was originally called Franklin.");
        AppConstants.allQuotesList.add("In the U.S. a pig has to weigh more than 180 lbs to be called a hog.");
        AppConstants.allQuotesList.add("Bloodhounds can track a man by smell for up to 100 miles.");
        AppConstants.allQuotesList.add("Beavers have orange teeth.");
        AppConstants.allQuotesList.add("The woodpecker can hammer wood up to 16 times per second.");
        AppConstants.allQuotesList.add("Mount Everest rises a few millimeters every year.");
        AppConstants.allQuotesList.add("Snails can sleep for up to three years.");
        AppConstants.allQuotesList.add("The pupils in goats' eyes are rectangular.");
        AppConstants.allQuotesList.add("Jousting is the official sport in the state of Maryland.");
        AppConstants.allQuotesList.add("Bees' wings beat 11,400 times per minute.");
        AppConstants.allQuotesList.add("The pound sign, or #, is called an octothorp.");
        AppConstants.allQuotesList.add("The Statue of Liberty wears a size 879 sandal.");
        AppConstants.allQuotesList.add("If there are two full moons in a month, the second one is called a blue moon.");
        AppConstants.allQuotesList.add("You breathe in about 13 pints of air every minute.");
        AppConstants.allQuotesList.add("A gallon of water weighs 8.34 pounds.");
        AppConstants.allQuotesList.add("The sun evaporates about a trillion tons of water a day.");
        AppConstants.allQuotesList.add("Sound travels quicker in water than in air.");
        AppConstants.allQuotesList.add("A group of cats is called a clowder.");
        AppConstants.allQuotesList.add("Human eyes have over two million working parts.");
        AppConstants.allQuotesList.add("There are approximately 9,000 taste buds on your tongue.");
        AppConstants.allQuotesList.add("Raindrops can fall as fast as 20 miles per hour.");
        AppConstants.allQuotesList.add("Polar bear fur is transparent, not white.");
        AppConstants.allQuotesList.add("Lobsters can live up to 50 years.");
        AppConstants.allQuotesList.add("About 85% of the world's population is right-handed.");
        AppConstants.allQuotesList.add("The first traffic light was in use in London in 1868, before the advent of cars.");
        AppConstants.allQuotesList.add("Fresh cranberries can be bounced like a rubber ball.");
        AppConstants.allQuotesList.add("A group of a dozen or more cows is called a 'flink.'");
        AppConstants.allQuotesList.add("Astronauts actually get taller when in space.");
        AppConstants.allQuotesList.add("A fifteen-year-old boy invented earmuffs in 1873.");
        AppConstants.allQuotesList.add("There is a ranch in Texas that is bigger than the entire state of Rhode Island.");
        AppConstants.allQuotesList.add("The dot over the letter i is called a tittle.");
        AppConstants.allQuotesList.add("Cows do not have upper front teeth.");
        AppConstants.allQuotesList.add("The great white shark can go up to three months between meals.");
        AppConstants.allQuotesList.add("During the Boston Tea Party, 342 chests of tea were thrown into the harbor.");
        AppConstants.allQuotesList.add("Pluto takes 248 years to orbit the sun once.");
        AppConstants.allQuotesList.add("Camels have three eyelids.");
        AppConstants.allQuotesList.add("454 U.S. dollar bills weigh exactly one pound.");
        AppConstants.allQuotesList.add("Dairy cows drink up to 50 gallons of water per day.");
        AppConstants.allQuotesList.add("The most common name for a pet goldfish is 'Jaws.'");
        AppConstants.allQuotesList.add("A nautical mile is 800 feet longer than a land mile.");
        AppConstants.allQuotesList.add("Antarctica has as much ice as the Atlantic Ocean has water.");
        AppConstants.allQuotesList.add("To temporarily revive your ballpoint pen, dip the tip into hot water for a few seconds.");
        AppConstants.allQuotesList.add("Wrapping rubber bands around the ends of hangers can prevent clothes from slipping off.");
        AppConstants.allQuotesList.add("Replacing your car's air filter can improve gas mileage by 10 percent.");
        AppConstants.allQuotesList.add("A chalkboard eraser is one of the best ways to wipe a foggy windshield.");
        AppConstants.allQuotesList.add("Candles will burn longer and drip less if they are placed in the freezer a few hours before using.");
        AppConstants.allQuotesList.add("Knots come out easier if you sprinkle talcum powder on them.");
        AppConstants.allQuotesList.add("You can tell which day a loaf of bread was baked by the color of its plastic twist tag.");
        AppConstants.allQuotesList.add("Over 50 percent of your body heat is lost through your head and neck.");
        AppConstants.allQuotesList.add("Dieting by not eating will actually make your body start conserving calories as fat.");
        AppConstants.allQuotesList.add("Smile more - every two thousand frowns creates one wrinkle.");
        AppConstants.allQuotesList.add("Rinsing bacon under cold water before frying can reduce the amount it shrinks by almost 50 percent.");
        AppConstants.allQuotesList.add("Refrigerating apples can help them last up to 10 times longer than those left at room temperature.");
        AppConstants.allQuotesList.add("While chopping onions, hold a piece of bread between your lips to keep your eyes from watering.");
        AppConstants.allQuotesList.add("Place an apple in the bag with your potatoes to keep them from budding.");
        AppConstants.allQuotesList.add("Place a slice of bread in the storage container to keep cookies soft when storing.");
        AppConstants.allQuotesList.add("To keep an ice cream cone from dripping, stuff a miniature marshmallow into the bottom of the cone.");
        AppConstants.allQuotesList.add("To take lumps out of a bag of sugar, place it in the refrigerator for 24 hours.");
        AppConstants.allQuotesList.add("To remove crayon marks from walls, use a hairdryer to heat the wax.");
        AppConstants.allQuotesList.add("To make a zipper slide up and down more smoothly, rub a bar of soap over the teeth.");
        AppConstants.allQuotesList.add("Wipe the leaves of your plants with the soft inside of a banana skin to bring up shine and remove dust.");
        AppConstants.allQuotesList.add("To clean paint off your hands, use olive oil - it softens the paint and makes it easy to remove.");
        AppConstants.allQuotesList.add("To fix a button about to fall off, dab a little clear nail polish over the threads holding it on.");
        AppConstants.allQuotesList.add("Forty-six percent of leisure visitors to downtown New York City come from outside the United States.");
        AppConstants.allQuotesList.add("New York taxi drivers collectively speak 60 languages.");
        AppConstants.allQuotesList.add("New York City is made up of 50 islands.");
        AppConstants.allQuotesList.add("The strike note of The Liberty Bell is E flat.");
        AppConstants.allQuotesList.add("Pigs were banished from Philadelphia's city streets in 1710.");
        AppConstants.allQuotesList.add("Philadelphia was the first capital of the United States.");
        AppConstants.allQuotesList.add("Forty percent of America's population lives within a one-day drive to Philadelphia.");

        //--Version V-1.1
        AppConstants.allQuotesList.add("It is against the law to put pretzels in bags in Philadelphia.");
        AppConstants.allQuotesList.add("One in six doctors in America was trained in Philadelphia.");
        AppConstants.allQuotesList.add("The shoreline at Wildwood grows almost 100 feet per year.");
        AppConstants.allQuotesList.add("Cape May is the oldest seashore resort in America.");
        AppConstants.allQuotesList.add("In the game Monopoly, the properties are named after streets in Atlantic City.");
        AppConstants.allQuotesList.add("Long Beach Island was once frequented by pirates.");
        AppConstants.allQuotesList.add("There is a town called Jersey Shore in Pennsylvania.");
        AppConstants.allQuotesList.add("The Wildwood Boardwalk extends nearly two miles and has more than 70,000 wooden planks.");
        AppConstants.allQuotesList.add("The average turtle can't reproduce until it's 25 years old.");
        AppConstants.allQuotesList.add("The oldest living animal ever found was a 405 year-old clam, named Ming by researchers.");
        AppConstants.allQuotesList.add("More than 180 countries celebrate Earth Day together every April 22nd.");
        AppConstants.allQuotesList.add("At 5 feet, the whooping crane is the tallest bird in North America.");
        AppConstants.allQuotesList.add("A full-grown tree produces enough oxygen to support a family of four.");
        AppConstants.allQuotesList.add("Unlike your housecat, the Siberian tiger actually loves to swim!");
        AppConstants.allQuotesList.add("A tiger's night vision is six times better than a human's.");
        AppConstants.allQuotesList.add("More Siberian tigers live in zoos than in the wild.");
        AppConstants.allQuotesList.add("The jaguar, the largest cat in the Western Hemisphere, once lived all over the southern US.");
        AppConstants.allQuotesList.add("The giant panda can eat up to 83 lbs of bamboo a day.");
        AppConstants.allQuotesList.add("Wildlife Forever has helped plant 132,420 trees in America since its founding in 1987.");
        AppConstants.allQuotesList.add("Manhattan Island was once home to as many different species as Yellowstone National Park.");
        AppConstants.allQuotesList.add("Dogs can make about 10 sounds, cats make about 100.");
        AppConstants.allQuotesList.add("A Pelican can hold more food in its beak than its belly.");
        AppConstants.allQuotesList.add("The average cat can jump 5 times as high as its tail is long.");
        AppConstants.allQuotesList.add("Flying fish leap out of the water at 20 mph or more, and can glide for over 500 feet.");
        AppConstants.allQuotesList.add("The roadrunner chases after its prey at a blurring speed of up to 25 mph.");
        AppConstants.allQuotesList.add("A chameleon shoots out its tongue to catch prey at speeds faster than a fighter jet.");
        AppConstants.allQuotesList.add("The archer fish can spit water up to 7 feet to shoot down bugs from overhanging leaves.");
        AppConstants.allQuotesList.add("The spotted skunk does a handstand to warn off its enemies before it sprays its stench.");
        AppConstants.allQuotesList.add("A male cricket's ear is located on the tibia of its leg.");
        AppConstants.allQuotesList.add("Spiny lobsters migrate in groups of 50 or more, forming a conga line on the ocean floor.");
        AppConstants.allQuotesList.add("The National Park Service manages over 350 parks on 80 million acres of public land.");
        AppConstants.allQuotesList.add("With an average life expectancy of 81.2 years, the people of Okinawa, Japan live the longest.");
        AppConstants.allQuotesList.add("Pilates stretches your muscles, improving your posture and helping you appear taller.");
        AppConstants.allQuotesList.add("Stepping out for a walk every day can actually help you sleep better at night.");
        AppConstants.allQuotesList.add("After working out, it takes 5 hours for your body temperature to return to normal.");
        AppConstants.allQuotesList.add("Turning the faucet off while brushing your teeth can save up to 5 gallons of water.");
        AppConstants.allQuotesList.add("It takes more water to fill a bathtub than it does to enjoy a nice, warm shower.");
        AppConstants.allQuotesList.add("On average, a laptop uses half as much energy as a desktop computer.");
        AppConstants.allQuotesList.add("The average bar of soap lasts twice as long as a bottle of body wash.");
        AppConstants.allQuotesList.add("Recycled paper is made using 40% less energy than normal paper.");
        AppConstants.allQuotesList.add("Every ton of recycled paper saves about 17 trees.");
        AppConstants.allQuotesList.add("Steel is 100% recyclable.");
        AppConstants.allQuotesList.add("Most rechargeable batteries can be recharged up to 1,000 times.");
        AppConstants.allQuotesList.add("Manufacturing recycled goods uses up to 95% less energy than using raw materials.");
        AppConstants.allQuotesList.add("Hybrid cars produce up to 75% less pollution than other vehicles.");
        AppConstants.allQuotesList.add("A tankless water heater uses half the energy of a standard model.");
        AppConstants.allQuotesList.add("Baking soda makes a great scouring cleanser, and it's naturally chemical-free.");
        AppConstants.allQuotesList.add("100% recyclable, old newspapers are great for washing windows.");
        AppConstants.allQuotesList.add("An egg that is fresh will sink in water, but a stale one won't.");
        AppConstants.allQuotesList.add("When thirsty, a camel can drink 25 gallons of water in less than three minutes.");
        AppConstants.allQuotesList.add("In one day, a full-grown oak tree expels 7 tons of water through its leaves.");
        AppConstants.allQuotesList.add("There is a museum of strawberries in Belgium.");
        AppConstants.allQuotesList.add("The mango is the most consumed fruit in the world.");
        AppConstants.allQuotesList.add("On average a strawberry has 200 seeds on it.");
        AppConstants.allQuotesList.add("A strawberry is not an actual berry but a banana is.");
        AppConstants.allQuotesList.add("Fresh apples float because 25 percent of their volume is air.");
        AppConstants.allQuotesList.add("The pomegranate is one of the oldest fruits known to man.");
        AppConstants.allQuotesList.add("The peach was the first fruit to be eaten on the moon.");
        AppConstants.allQuotesList.add("The optimum depth of water in a birdbath is two and a half inches.");
        AppConstants.allQuotesList.add("A pineapple is neither an apple or a pine. It is, in fact, a large berry.");
        AppConstants.allQuotesList.add("Only female mosquitoes bite.");
        AppConstants.allQuotesList.add("A polar bear cannot be seen by an infrared camera, due to its transparent fur.");
        AppConstants.allQuotesList.add("A spider's silk is stronger than steel.");
        AppConstants.allQuotesList.add("The planet Saturn has a density lower than water. It would float if placed in water.");
        AppConstants.allQuotesList.add("Twins have a very high occurrence of left handedness.");
        AppConstants.allQuotesList.add("The fear of vegetables is called lachanophobia.");
        AppConstants.allQuotesList.add("There are over 2,000 different species of cactuses.");
        AppConstants.allQuotesList.add("The chicken is the closest living relative of Tyrannosaurus Rex.");
        AppConstants.allQuotesList.add("All scorpions glow.");
        AppConstants.allQuotesList.add("Potatoes have more chromosomes than humans.");
        AppConstants.allQuotesList.add("A full moon is nine times brighter than a half moon.");
        AppConstants.allQuotesList.add("More babies are born at night than during the day.");
        AppConstants.allQuotesList.add("The human brain takes up 2% of human body weight but uses 20% of its energy.");
        AppConstants.allQuotesList.add("There are more species of fish in the Amazon river than in the Atlantic Ocean.");
        AppConstants.allQuotesList.add("You transfer more germs shaking hands than kissing.");
        AppConstants.allQuotesList.add("Poison Ivy is not Ivy and Poison Oak is not an Oak. They are both part of the Cashew family.");
        AppConstants.allQuotesList.add("Plants, like humans, can run a fever if they are sick.");
        AppConstants.allQuotesList.add("Over half of the world's geysers are found in Yellowstone National Park.");
        AppConstants.allQuotesList.add("A group of geese on the ground is a gaggle, a group of geese in the air is a skein.");
        AppConstants.allQuotesList.add("Polar bears can smell a seal from 20 miles away.");
        AppConstants.allQuotesList.add("Armadillos have four babies at a time and they are always all the same sex.");
        AppConstants.allQuotesList.add("The only insect that can turn its head is a praying mantis.");
        AppConstants.allQuotesList.add("Alaska was bought from Russia for about 2 cents an acre.");
        AppConstants.allQuotesList.add("A dog's average body temperature is 101 degrees Fahrenheit.");
        AppConstants.allQuotesList.add("The average housefly lives for one month.");
        AppConstants.allQuotesList.add("The common garden worm has five pairs of hearts.");
        AppConstants.allQuotesList.add("Flamingos can only eat with their heads upside down.");
        AppConstants.allQuotesList.add("A group of twelve or more cows is called a flink.");
        AppConstants.allQuotesList.add("A group of goats is called a trip.");
        AppConstants.allQuotesList.add("An alligator can go through 3,000 teeth in a lifetime.");
        AppConstants.allQuotesList.add("There are more chickens than people in the world.");
        AppConstants.allQuotesList.add("Penguins can jump 6 feet.");
        AppConstants.allQuotesList.add("There are approximately 7,000 feathers on an eagle.");
        AppConstants.allQuotesList.add("The only lizard that has a voice is the Gecko.");
        AppConstants.allQuotesList.add("A rhinoceros horn is made of compacted hair.");
        AppConstants.allQuotesList.add("Dolphins sleep with one eye open.");
        AppConstants.allQuotesList.add("Owls are one of the only birds who can see the color blue.");
        AppConstants.allQuotesList.add("A duck has three eyelids.");
        AppConstants.allQuotesList.add("Tigers have striped skin, not just striped fur.");
        AppConstants.allQuotesList.add("The muzzle of a lion is like a fingerprint - no two lions have the same pattern of whiskers.");
        AppConstants.allQuotesList.add("A cat has 32 muscles in each ear.");
        AppConstants.allQuotesList.add("The hippopotamus has the capability to remain underwater for as long as five minutes.");
        AppConstants.allQuotesList.add("Honeybees have hair on their eyes.");
        AppConstants.allQuotesList.add("Most elephants weigh less than the tongue of a blue whale.");
        AppConstants.allQuotesList.add("If a sheep and a goat mate the offspring is called a geep.");
        AppConstants.allQuotesList.add("Pistol shrimp can make a noise loud enough to break glass.");
        AppConstants.allQuotesList.add("Some dinosaurs were as small as chickens.");
        AppConstants.allQuotesList.add("Male moose shed their antlers every winter and grow a new pair the next year.");
        AppConstants.allQuotesList.add("Mountain goats aren't actually goats. They are antelopes.");
        AppConstants.allQuotesList.add("Koalas only drink water in extreme heat or drought.");
        AppConstants.allQuotesList.add("Bees are born fully grown.");
        AppConstants.allQuotesList.add("Ferret comes from the Latin word for little thief.");
        AppConstants.allQuotesList.add("Cats have 2 sets of vocal cords: one for purring and one for meowing.");
        AppConstants.allQuotesList.add("Some bears build nests in trees for sunbathing and resting.");
        AppConstants.allQuotesList.add("A group of jellyfish is called a smack.");
        AppConstants.allQuotesList.add("The indentation in the middle of the area between the nose and the upper lip is called the philtrum.");
        AppConstants.allQuotesList.add("Women blink nearly twice as much as men.");
        AppConstants.allQuotesList.add("The human jaw can generate a force up to 200 pounds on the molars.");
        AppConstants.allQuotesList.add("Men get hiccups more than women.");
        AppConstants.allQuotesList.add("The human brain is about 80% water.");
        AppConstants.allQuotesList.add("The fastest growing nail is on the middle finger.");
        AppConstants.allQuotesList.add("The brain operates on the same amount of power as a 10-watt light bulb.");
        AppConstants.allQuotesList.add("Like fingerprints, everyone's tongue print is different.");
        AppConstants.allQuotesList.add("The average person falls asleep in seven minutes.");
        AppConstants.allQuotesList.add("The average woman is 5 inches shorter than the average man.");
        AppConstants.allQuotesList.add("Your big toe only has 2 bones and the rest have 3.");
        AppConstants.allQuotesList.add("The average person takes 23,000 breaths a day.");
        AppConstants.allQuotesList.add("The state of Florida is bigger than England.");
        AppConstants.allQuotesList.add("Broadway is one of the longest streets in the world. It is 150 miles long.");
        AppConstants.allQuotesList.add("Mount Whitney, the highest mountain in the continental United States, and Zabriskie Point, the lowest point in the United States, are less than eighty miles apart.");
        AppConstants.allQuotesList.add("Hawaii is moving toward Japan at the rate of almost 4 inches per year.");
        AppConstants.allQuotesList.add("India has more English speakers than the United States.");
        AppConstants.allQuotesList.add("In Youngstown Ohio, it is against the law to run out of gas.");
        AppConstants.allQuotesList.add("Tennessee was previously named Franklin after Benjamin Franklin.");
        AppConstants.allQuotesList.add("The official color of California's Golden Gate Bridge is International Orange.");
        AppConstants.allQuotesList.add("Most lipstick contains fish scales.");
        AppConstants.allQuotesList.add("It is not possible to tickle yourself.");
        AppConstants.allQuotesList.add("Every state except Maine, Alaska, and Hawaii is home to at least one species of venomous snake.");
        AppConstants.allQuotesList.add("Antarctica is the only continent with no owls.");
        AppConstants.allQuotesList.add("There are 293 ways to make change for a dollar.");
        AppConstants.allQuotesList.add("India has a Bill of Rights for cows.");
        AppConstants.allQuotesList.add("In Albania, nodding your head means no and shaking your head means yes.");
        AppConstants.allQuotesList.add("Shakespeare invented the word assassination and bump.");
        AppConstants.allQuotesList.add("Some violins contain 70 separate pieces of wood.");
        AppConstants.allQuotesList.add("French author Michel Thayer published a 233 page novel which has no verbs.");
        AppConstants.allQuotesList.add("Australia is the only continent without an active volcano.");
        AppConstants.allQuotesList.add("The dots on a domino are called pips.");
        AppConstants.allQuotesList.add("111,111,111 x 111,111,111 = 12,345,678,987,654,321");
        AppConstants.allQuotesList.add("The number sign # is called an octothorpe.");
        AppConstants.allQuotesList.add("Tug-of-war was an Olympic sport in the early 1900's.");
        AppConstants.allQuotesList.add("The name of the city we call Bangkok is 115 letters long in the Thai language.");
        AppConstants.allQuotesList.add("In Ancient Greece throwing an apple to a woman was considered a marriage proposal.");
        AppConstants.allQuotesList.add("Karate originated in India.");
        AppConstants.allQuotesList.add("The infinity sign is called a lemniscate.");
        AppConstants.allQuotesList.add("Children grow faster during springtime.");
        AppConstants.allQuotesList.add("Relative to size, the tongue is the strongest muscle in the human body.");
        AppConstants.allQuotesList.add("It takes an interaction of 72 muscles to produce human speech.");
        AppConstants.allQuotesList.add("The only jointless bone in the body is in your throat.");
        AppConstants.allQuotesList.add("Sailors once thought wearing gold earrings improved eyesight.");
        AppConstants.allQuotesList.add("On average a man spends about five months of his life shaving.");
        AppConstants.allQuotesList.add("Our eyes are always the same size from birth, but our nose and ears never stop growing.");
        AppConstants.allQuotesList.add("In the average lifetime, a person will walk the equivalent of 5 times around the equator.");
        AppConstants.allQuotesList.add("Your skull is made up of 29 different bones.");
        AppConstants.allQuotesList.add("Every hour more than one billion cells in the body must be replaced.");
        AppConstants.allQuotesList.add("Women's hearts beat faster than men's hearts.");
        AppConstants.allQuotesList.add("The average human dream lasts only 2 to 3 seconds.");
        AppConstants.allQuotesList.add("Six-year-olds laugh an average of 300 times a day. Adults only laugh 15 to 100 times a day.");
        AppConstants.allQuotesList.add("Brain waves can power an electric train.");
        AppConstants.allQuotesList.add("Children have more taste buds than adults.");
        AppConstants.allQuotesList.add("Right handed people tend to chew food on the right side and lefties chew on the left.");
        AppConstants.allQuotesList.add("You burn more calories sleeping than you do watching television.");
        AppConstants.allQuotesList.add("Pomology is the study of fruit.");
        AppConstants.allQuotesList.add("The most widely eaten fruit in America is the banana.");
        AppConstants.allQuotesList.add("Cranberries are sorted for ripeness by bouncing them.");
        AppConstants.allQuotesList.add("A cucumber consists of 96% water.");
        AppConstants.allQuotesList.add("The only food that does not spoil is honey.");
        AppConstants.allQuotesList.add("The most popular ice cream flavor is vanilla.");
        AppConstants.allQuotesList.add("Vanilla is used to make chocolate.");
        AppConstants.allQuotesList.add("Bamboo (the world's tallest grass) can grow up to 90cm in a day.");
        AppConstants.allQuotesList.add("One lump of sugar is equivalent to three feet of sugar cane.");
        AppConstants.allQuotesList.add("A lemon contains more sugar than a strawberry.");
        AppConstants.allQuotesList.add("An average of three billion cups of tea are consumed daily worldwide.");
        AppConstants.allQuotesList.add("Until the nineteenth century, solid blocks of tea were used as money in Siberia.");
        AppConstants.allQuotesList.add("Wild camels once roamed Arizona's deserts.");
        AppConstants.allQuotesList.add("New York was the first state to require cars to have license plates.");
        AppConstants.allQuotesList.add("Hawaii is further south than Florida.");
        AppConstants.allQuotesList.add("Miami installed the first ATM for rollerbladers.");
        AppConstants.allQuotesList.add("Clearwater, Florida has the highest rate of lightning strikes per capita in the US.");
        AppConstants.allQuotesList.add("Hawaii has its own time zone.");
        AppConstants.allQuotesList.add("Hawaii is the only US state that grows coffee.");
        AppConstants.allQuotesList.add("Oregon has more ghost towns than any other US city.");
        AppConstants.allQuotesList.add("The world's largest silver nugget (1,840 lbs) was found in 1894 near Aspen, Colorado.");
        AppConstants.allQuotesList.add("Louisiana is home to over 80% of the world's crayfish.");
        AppConstants.allQuotesList.add("New Jersey is home to the world's first drive-in movie theater.");
        AppConstants.allQuotesList.add("George Washington took the oath of office in New York City in 1789.");
        AppConstants.allQuotesList.add("Cleveland, OH is home to the first electric traffic lights.");
        AppConstants.allQuotesList.add("South Carolina is home to the first tea farm in the U.S.");
        AppConstants.allQuotesList.add("The typewriter was invented in Milwaukee, WI in 1867.");
        AppConstants.allQuotesList.add("The term rookies comes from a Civil War term, reckie, which was short for recruit.");
        AppConstants.allQuotesList.add("Taft was the heaviest U.S. President at 329lbs; Madison was the smallest at 100lbs.");
        AppConstants.allQuotesList.add("Harry Truman was the last U.S. President to not have a college degree.");
        AppConstants.allQuotesList.add("Abraham Lincoln was the tallest U.S. President at 6'4\". " +
                "James Madison was the shortest at 5'4\".");
        AppConstants.allQuotesList.add("Franklin Roosevelt was related to 5 U.S. Presidents by blood and 6 by marriage.");
        AppConstants.allQuotesList.add("Thomas Jefferson invented the coat hanger.");
        AppConstants.allQuotesList.add("Theodore Roosevelt had a pet bear while in office.");
        AppConstants.allQuotesList.add("President Warren G. Harding once lost white house china in a poker game.");
        AppConstants.allQuotesList.add("Ulysses Simpson Grant once got a $20.00 fine for speeding on his horse.");
        AppConstants.allQuotesList.add("President William Taft weighed over 300 lbs and once got stuck in the white house bathtub.");
        AppConstants.allQuotesList.add("President William McKinley had a pet parrot that he named" +
                " \"Washington Post.\"");
        AppConstants.allQuotesList.add("Harry S. Truman's middle name is S.");
        AppConstants.allQuotesList.add("Before Thomas Jefferson took office people bowed to the president, rather than shaking his hand.");
        AppConstants.allQuotesList.add("The youngest U.S. president to be in office was Theodore Roosevelt at age 42.");
        AppConstants.allQuotesList.add("People don't sneeze when they are asleep because the nerves involved in the sneeze reflex are also resting.");
        AppConstants.allQuotesList.add("Only male fireflies can fly.");
        AppConstants.allQuotesList.add("Most Koala bears sleep about 22 hours a day.");
        AppConstants.allQuotesList.add("The Venus flytrap can eat a whole cheeseburger.");
        AppConstants.allQuotesList.add("A baby caribou can outrun its mother at 3 days old.");
        AppConstants.allQuotesList.add("In 1859, 24 rabbits were released in Australia. Within 6 years, the population grew to 2 million.");
        AppConstants.allQuotesList.add("Butterflies taste with their hind feet.");
        AppConstants.allQuotesList.add("A strand from the web of a golden spider is as strong as a steel wire of the same size.");
        AppConstants.allQuotesList.add("Vultures can fly for six hours without flapping their wings.");
        AppConstants.allQuotesList.add("The bumblebee bat is the smallest mammal on Earth. It weighs less than a penny.");
        AppConstants.allQuotesList.add("The Valley of Square Trees in Panama is the only known place in the world where trees have rectangular trunks.");
        AppConstants.allQuotesList.add("In some cultures' telling of Snow White, the dwarves are thieves.");
        AppConstants.allQuotesList.add("The original Cinderella was Egyptian and wore fur slippers.");
        AppConstants.allQuotesList.add("The number 1 or the word One appears on the dollar bill 16 times.");
        AppConstants.allQuotesList.add("Pound cake got its name from the original recipe which called for a pound of butter.");
        AppConstants.allQuotesList.add("The can opener was invented 48 years after the can.");
        AppConstants.allQuotesList.add("Jack-O-Lanterns were originally made out of turnips.");
        AppConstants.allQuotesList.add("Jousting is the official sport of Maryland.");
        AppConstants.allQuotesList.add("If you shake a can of mixed nuts, the larger nuts will rise to the top.");
        AppConstants.allQuotesList.add("2nd Street is the most common street name in the United States; First Street is the 6th most common.");
        AppConstants.allQuotesList.add("The Mayflower only held 102 People.");
        AppConstants.allQuotesList.add("The ridges on the sides of coins are called reeding or milling.");
        AppConstants.allQuotesList.add("The plastic things on the end of shoelaces are called aglets.");
        AppConstants.allQuotesList.add("Neckties were first worn in Croatia, which is why they were called cravats.");
        AppConstants.allQuotesList.add("The quartz crystal in your wristwatch vibrates 32,768 times a second.");
        AppConstants.allQuotesList.add("Barbie's full name is Barbara Millicent Roberts.");
        AppConstants.allQuotesList.add("The first TV toy commercial aired in 1946 for Mr. Potato Head.");
        AppConstants.allQuotesList.add("If done perfectly, any Rubick's Cube combination can be solved in 17 turns.");
        AppConstants.allQuotesList.add("The side of a hammer is called a cheek.");
        AppConstants.allQuotesList.add("Rubber bands last longer when refrigerated.");
        AppConstants.allQuotesList.add("Dueling is legal in Paraguay as long as both parties are registered blood donors.");
        AppConstants.allQuotesList.add("In Athens, Greece, a driver's license can be taken away by law if the driver is deemed either unbathed or poorly dressed.");
        AppConstants.allQuotesList.add("In Texas, it is illegal to graffiti someone's cow.");
        AppConstants.allQuotesList.add("Less than 2% of the water on Earth is fresh.");
        AppConstants.allQuotesList.add("A cubic mile of fog is made up of less than a gallon of water.");
        AppConstants.allQuotesList.add("Meteorologists claim they're right 85% of the time.");
        AppConstants.allQuotesList.add("The Saturn V moon rocket consumed 15 tons of fuel per second.");
        AppConstants.allQuotesList.add("A manned rocket can reach the moon in less time than it took a stagecoach to travel the length of England.");
        AppConstants.allQuotesList.add("At room temperature, the average air molecule travels at the speed of a rifle bullet.");
        AppConstants.allQuotesList.add("The average lead pencil can draw a line 35 miles long or write roughly 50,000 English words.");
        AppConstants.allQuotesList.add("The first lollipop was invented in Connecticut.");
        AppConstants.allQuotesList.add("The Lollipop was named after one of the most famous Racehorses in the early 1900s, Lolly Pop.");
        AppConstants.allQuotesList.add("Buzz Aldrin was one of the first men on the moon. His mother's maiden name was also Moon.");
        AppConstants.allQuotesList.add("If you had 1 billion dollars and spent 1 thousand dollars a day, it would take you 2,749 years to spend it all.");
        AppConstants.allQuotesList.add("Maine is the only state with a one-syllable name.");
        AppConstants.allQuotesList.add("In Germany the shhh sound means hurry up.");
        AppConstants.allQuotesList.add("The highest denomination issued by the U.S. was the 100,000 dollar bill.");
        AppConstants.allQuotesList.add("The White House was originally called the President's Palace. It became The White House in 1901.");
        AppConstants.allQuotesList.add("George Washington was the only unanimously elected President.");
        AppConstants.allQuotesList.add("John Adams was the only President to be defeated by his Vice President, Thomas Jefferson.");
        AppConstants.allQuotesList.add("New York City has 722 miles of subway track.");
        AppConstants.allQuotesList.add("Manatees' eyes close in a circular motion, much like the aperture of a camera.");
        AppConstants.allQuotesList.add("Even though it is nearly twice as far away from the Sun as Mercury, Venus is by far the hottest planet.");
        AppConstants.allQuotesList.add("The nothingness of a black hole generates a sound in the key of B flat.");
        AppConstants.allQuotesList.add("Horses can't vomit.");
        AppConstants.allQuotesList.add("A crocodile can't stick out its tongue.");
        AppConstants.allQuotesList.add("Babies are born with about 300 separate bones. Adults have 206.");
        AppConstants.allQuotesList.add("Newborn babies cannot cry tears for at least three weeks.");
        AppConstants.allQuotesList.add("A day on Venus lasts longer than a year on Venus.");
        AppConstants.allQuotesList.add("Squirrels lose more than half of the nuts they hide.");
        AppConstants.allQuotesList.add("It cost the United States Mint two cents to produce and distribute a penny in 2012.");
        AppConstants.allQuotesList.add("The penny was the first U.S. coin to feature the likeness of an actual person.");
        AppConstants.allQuotesList.add("Forty percent of twins invent their own language.");
        AppConstants.allQuotesList.add("In South Korea, it is against the rules for a professional baseball player to wear cabbage leaves inside of his hat.");
        AppConstants.allQuotesList.add("Curly hair follicles are oval, while straight hair follicles are round.");
        AppConstants.allQuotesList.add("George Washington had false teeth made of gold, ivory, and lead - but never wood.");
        AppConstants.allQuotesList.add("Napoleon Bonaparte was not short. At 5' 7\", " +
                "he was of average height for his time.");
        AppConstants.allQuotesList.add("The Inca built the largest and wealthiest empire in South America, but had no concept of money.");
        AppConstants.allQuotesList.add("It is against the law to use \"The Star Spangled Banner\" as dance music in Massachusetts.");
        AppConstants.allQuotesList.add("Queen Cleopatra of Egypt was not actually Egyptian, but a Macedonian Greek.");
        AppConstants.allQuotesList.add("Early football fields were painted with both horizontal and vertical lines, creating a pattern that resembled a gridiron.");
        AppConstants.allQuotesList.add("Two national capitals are named after U.S. presidents: Washington, D.C., and Monrovia, the capital of Liberia.");
        AppConstants.allQuotesList.add("The first spam message was transmitted over telegraph wires in 1864.");
        AppConstants.allQuotesList.add("A pearl can be dissolved by vinegar.");
        AppConstants.allQuotesList.add("Queen Isabella I of Spain, who funded Columbus' voyage across the ocean, claimed to have only bathed twice in her life.");
        AppConstants.allQuotesList.add("The longest attack of hiccups ever lasted 68 years.");
        AppConstants.allQuotesList.add("Until its demolition in 2012, one percent of Greenland's total population lived in a single apartment building called Blok P.");
        AppConstants.allQuotesList.add("A bolt of lightning can reach temperatures hotter than 50,000 degrees Fahrenheit - five times hotter than the sun.");
        AppConstants.allQuotesList.add("At the deepest point in the ocean, the water pressure is equivalent to having about 50 jumbo jets piled on top of you.");
        AppConstants.allQuotesList.add("In only 7.6 billion years, the sun will reach its maximum size and will shine 3,000 times brighter.");
        AppConstants.allQuotesList.add("The state of Alabama once financed the construction of a bridge by holding a rooster auction.");
        AppConstants.allQuotesList.add("Federal law once allowed the government to quarantine people who came in contact with aliens.");
        AppConstants.allQuotesList.add("There are 21 \"secret\" highways that are part of the " +
                "Interstate Highway System. They are not identified as such by road signs.");
        AppConstants.allQuotesList.add("The aphid, a small, sap-sucking insect, is born pregnant.");
        AppConstants.allQuotesList.add("John Wilkes Booth's brother once saved the life of Abraham Lincoln's son.");
        AppConstants.allQuotesList.add("The Pacific Ocean is eight inches higher than the Atlantic Ocean at the Panama Canal.");
        AppConstants.allQuotesList.add("It is illegal in the United Kingdom to handle salmon in suspicious circumstances.");
        AppConstants.allQuotesList.add("It is illegal to play annoying games in the street in the United Kingdom.");
        AppConstants.allQuotesList.add("Tennis was originally played with bare hands.");
        AppConstants.allQuotesList.add("There are ten times more microbial cells than human cells in our bodies.");
        AppConstants.allQuotesList.add("-40 degrees Fahrenheit is the same temperatures as -40 degrees Celsius.");
        AppConstants.allQuotesList.add("John Tyler had more children than any other U.S. president. The last of his 15 children was born when he was 70 years old.");
        AppConstants.allQuotesList.add("Dolphins are unable to smell.");
        AppConstants.allQuotesList.add("Charlie Chaplin failed to make the finals of a Charlie Chaplin look-alike contest.");
        AppConstants.allQuotesList.add("The name of the city of Portland, Oregon was decided by a coin toss. The name that lost was Boston.");
        AppConstants.allQuotesList.add("Within five minutes of waking, 50 percent of a dream is forgotten. Within ten minutes, 90 percent of it is forgotten.");
        AppConstants.allQuotesList.add("All gondolas in Venice, Italy must be painted black unless they are carrying an important person.");
        AppConstants.allQuotesList.add("The letter J is the only letter in the alphabet that does not appear anywhere on the periodic table of the elements.");
        AppConstants.allQuotesList.add("'K' was chosen to stand for a strikeout in baseball because 'S' was being used to denote a sacrifice.");
        AppConstants.allQuotesList.add("The tradition of baseball managers wearing player uniforms started because the first managers were also players.");
        AppConstants.allQuotesList.add("George Washington feared being buried alive.");
        AppConstants.allQuotesList.add("A dimpled golf ball produces less drag and flies farther than a smooth golf ball would fly.");
        AppConstants.allQuotesList.add("When grazing or resting, cows tend to align their bodies with the magnetic north and south poles.");
        AppConstants.allQuotesList.add("President Chester A. Arthur owned 80 pairs of pants, which he changed several times per day.");
        AppConstants.allQuotesList.add("Cows do not have upper front teeth.");
        AppConstants.allQuotesList.add("Between 1979 and 1999, the planet Neptune was farther from the Sun than Pluto. This will happen again in 2227.");
        AppConstants.allQuotesList.add("When creating a mummy, Ancient Egyptians removed the brain by inserting a hook through the nostrils.");
        AppConstants.allQuotesList.add("All of the major candidates in the 1992, 1996, and 2008 U.S. presidential elections were left-handed.");
        AppConstants.allQuotesList.add("In Switzerland, it is illegal to own only one guinea pig because they are prone to loneliness.");
        AppConstants.allQuotesList.add("The first American gold rush happened in North Carolina, not California.");
        AppConstants.allQuotesList.add("Each year, the Moon moves away from Earth by about four centimeters.");
        AppConstants.allQuotesList.add("To make one pound of honey, a honeybee must tap about two million flowers.");

        //826

        AppConstants.allQuotesList.add("The most popular first name in the world is Muhammad!");
        AppConstants.allQuotesList.add("Every day 20 banks are robbed. The average take is $2,500!");
        AppConstants.allQuotesList.add("A Boeing 747 airliner holds 57,285 gallons of fuel.");
        AppConstants.allQuotesList.add("No piece of square dry paper can be folded more than 7 times in half!");
        AppConstants.allQuotesList.add("During your lifetime, you'll eat about 60,000 pounds of food, that's the weight of about 6 elephants!");
        AppConstants.allQuotesList.add("Recycling one glass jar, saves enough energy to watch T.V for 3 hours!");
        AppConstants.allQuotesList.add("More people use blue toothbrushes, than red ones!");
        AppConstants.allQuotesList.add("More money is spent on gardening than on any other hobby!");
        AppConstants.allQuotesList.add("Rice paper does not have any rice in it!");
        AppConstants.allQuotesList.add("Men are 6 times more likely to be struck by lightning than women!");
        AppConstants.allQuotesList.add("India was an Island Once.");
        AppConstants.allQuotesList.add("You grow 8mm while you are asleep.");
        AppConstants.allQuotesList.add("More than 50% of the people in the world have never made or received a telephone call.");
        AppConstants.allQuotesList.add("In every episode of Seinfeld there is a Superman somewhere.");
        AppConstants.allQuotesList.add("A duck's quack doesn't echo, and no one knows why.");
        AppConstants.allQuotesList.add("Outside the USA, Ireland is the largest software producing country in the world.");
        AppConstants.allQuotesList.add("The lifespan of a squirrel is about nine years.");
        AppConstants.allQuotesList.add("There are more than fifty different kinds of kangaroos.");
        AppConstants.allQuotesList.add("Money isn't made out of paper; it's made out of cotton. ");
        AppConstants.allQuotesList.add("On average, 12 newborns will be given to the wrong parents daily. ");
        AppConstants.allQuotesList.add("Donald Duck comics were banned from Finland because he doesn't wear any pants. ");
        AppConstants.allQuotesList.add("Ketchup was sold in the 1830s as medicine. ");
        AppConstants.allQuotesList.add("Leonardo da Vinci could write with one hand and draw with the other at the same time. ");
        AppConstants.allQuotesList.add("A tiny amount of liquor on a scorpion will make it instantly go mad and sting itself to death. ");
        AppConstants.allQuotesList.add("The strongest muscle in the body is the tongue.");
        AppConstants.allQuotesList.add("There is a city called Rome on every continent.");
        AppConstants.allQuotesList.add("A full moon is nine times brighter than a half moon.");
        AppConstants.allQuotesList.add("An average human loses about 200 head hairs per day.");
        AppConstants.allQuotesList.add("The Olympic was the sister ship of the Titanic, and she provided twenty-five years of service.");
        AppConstants.allQuotesList.add("1 in 5 of the world’s doctors are Russian.");
        AppConstants.allQuotesList.add("Venus is the only planet that rotates clockwise.");
        AppConstants.allQuotesList.add("California consumes more bottled water than any other product.");
        AppConstants.allQuotesList.add("It is estimated that millions of trees are planted by forgetful squirrels.");

    }
}
